
name: CI

on:
  push:
    branches: 
    - main
  

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      # Test of tests
      - name: Run tests once API is running
        run: cd test && sleep 60 && dotnet test